# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import inventory_pb2 as inventory__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17inventory_service.proto\x1a\x0finventory.proto\"(\n\x11\x43reateBookRequest\x12\x13\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x05.Book\"%\n\x12\x43reateBookResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04isbn\x18\x01 \x01(\t\"&\n\x0fGetBookResponse\x12\x13\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x05.Book2t\n\tInventory\x12\x37\n\nCreateBook\x12\x12.CreateBookRequest\x1a\x13.CreateBookResponse\"\x00\x12.\n\x07GetBook\x12\x0f.GetBookRequest\x1a\x10.GetBookResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEBOOKREQUEST._serialized_start=44
  _CREATEBOOKREQUEST._serialized_end=84
  _CREATEBOOKRESPONSE._serialized_start=86
  _CREATEBOOKRESPONSE._serialized_end=123
  _GETBOOKREQUEST._serialized_start=125
  _GETBOOKREQUEST._serialized_end=155
  _GETBOOKRESPONSE._serialized_start=157
  _GETBOOKRESPONSE._serialized_end=195
  _INVENTORY._serialized_start=197
  _INVENTORY._serialized_end=313
# @@protoc_insertion_point(module_scope)
